### ISSUE TITLE
Say Hi and introduce yourself!

### ISSUE THREAD

**Issue by jglovier** [jglovier/github-for-developers-squares-conf-2016#1]
Hello fellow developers! :wave: I'm really looking forward to our time together on Wednesday. In advance, I'd love for us to introduce ourselves just so we all feel a little more like we've had a chance to get acquainted. This will also be part of our learning session, and so you could consider this prework. Drop a comment in the thread below and tell as little or as much about yourself as you'd like, and maybe one interesting fact about yourself. I'll go first.

---

I'm Joel, and I'm a Lead Product Designer here at GitHub where I've been since 2013. I work remotely (as does about 55% of our company) from my home in Central Pennsylvania. I've been writing code since about 2005 (started by dorking around with CSS in Blogger themes), and I've been doing design since around 2004. 

One interesting fact about me is that I like to [tune import cars](https://github.com/jglovier/project-car).

You can find me on [Twitter here](https://twitter.com/jglovier), or [on the web here](http://joelglovier.com/). See ya Wednesday! :bow:

![bboy-jag](https://cloud.githubusercontent.com/assets/1319791/14793201/f223b358-0aeb-11e6-878a-81678f9eda85.gif)

**Comment by jesseschutt** [comment]
Hey All! I'm Jesse and I live in northern Wisconsin with my wife and 6 kiddos. I'm a backend developer at http://zaengle.com and I love [woodworking](http://instagram.com/jesseschutt)!

**Comment by jglovier** [comment]
@jschutt those awls are rad!

**Comment by courtneybradford** [comment]
@jglovier Agreed! Love your craftsmanship, @jschutt. Makes me miss my (very humble) furniture and woodworking projects. 

Howdy! That's what I'm supposed to say in Texas, right?

I'm Courtney, co-founder and principal designer at Telegraph Creative in Dallas. Our new site is on the way, in the meantime I'm teaching our [disinterested intern](https://www.instagram.com/p/m8XFn2vbQg/?tagged=fitzsits) about color theory. 

In all seriousness, in my spare time I enjoy working my vegetable/herb garden, backpacking, and nerding out over craft beers.

**Comment by jglovier** [comment]
@courtneybradford I need a disinterested intern, too. 😄

**Comment by joshmccray** [comment]
Hey!

I'm Josh. I make sure the undies keep flowing at [jockey.com](http://www.jockey.com). Hobbies include drinking too much coffee, [drawing dumb stuff](https://dribbble.com/JoshMcCray), and [instagrammin'](https://www.instagram.com/thejmccray/).

Fun fact: last summer we drove a 15 passenger van from Deadhorse, Alaska to Kenosha, Wisconsin.

See y'all tomorrow!

**Comment by jesseschutt** [comment]
@joshmccray Hey are you from Wisconsin?

**Comment by joshmccray** [comment]
@jschutt Yep! Good ol' Kenosha. Where in Wisco do you live??

**Comment by jesseschutt** [comment]
@joshmccray I'm way north of you! Northwest of Wausau by an hour

**Comment by raray** [comment]
I'm R.A. a Texas native and resident of McKinney. I write frontend code at [Lifeblue.com](http://lifeblue.com/). I've recently begun making craft soap.

**Comment by plasticmind** [comment]
Howdy, everyone! I'm Jesse Gardner, and I do front and back-end design and development for [Simply Recipes](http://www.simplyrecipes.com). My wife and I also [make soy wax candles](http://thoughtfulgardner.com) and have recently started small-scale farming. I also really enjoy [nature photography](http://instagram.com/plasticmind).

I won't be able to make it to the workshop because of travel issues, but I'd love to say hello at the main conference!

**Comment by jordankoschei** [comment]
Hey guys! I'm Jordan, and I'm a UX designer/front-end dev from the Hudson Valley (just north of NYC). Hm, something interesting about me... I live on the [oldest continuously-occupied street in North America](https://en.m.wikipedia.org/wiki/Huguenot_Street_Historic_District). Also, I'm really into regional trivia.

Looking forward to meeting you all!

**Comment by jupago** [comment]
Hi everyone! I'm JP, web designer based in New York. Trained in design, then transitioned to web development around 2008. First building table-based sites, then flash-based, up until now where I'm trying to keep up with standards. I mostly freelance so haven't taken advantage of github, looking forward to changing that today!

Interesting fact about me: I live at the highest natural point in Manhattan, so if they ever make a sequel for _the day after tomorrow_ I should be fine!

**Comment by steve-schultz** [comment]
Hey guys, I'm Steve. I am a designer at theberrics.com and theskateboardmag.com. Originally from northern Michigan now living in Los Angeles.

I skateboard a lot and brew beer occasionally.

**Comment by rjimenezhsc** [comment]
Hello everybody,

My name is Raul Jimenez and I work for Texas A&M Health Science Center developing web applications.
I enjoy working with anything related to technology, but when my retinas need rest I like working outside in my garden with my chickens and dogs.

Looking forward to this workshop!

**Comment by CarolynYalin** [comment]
Y'all late to the game... from Colorado via Canada. Freelancer, always looking to learn new tricks.

**Comment by beorn237** [comment]
Hey all! Name is Dustin. Freelance UI Designer and Developer.

![abedgun](https://cloud.githubusercontent.com/assets/868730/14863634/2401ff60-0c7c-11e6-9610-e4b4794b2106.gif)

**Comment by dialady** [comment]
Hi y'all, I'm Theresa Wagar.  I'm a website designer and developer for local businesses.  Excited to learn how to use Github better to help contribute to the Wordpress community. I live in Smithfield, Virginia (across the river from Williamsburg) with my hubby and two adorable cats (my kids are grown so we now have cats instead).

**Comment by dialady** [comment]
Hi y'all, I'm Theresa Wagar.  I'm a website designer and developer for local businesses.  Excited to learn how to use Github better to help contribute to the Wordpress community. I live in Smithfield, Virginia (across the river from Williamsburg) with my hubby and two adorable cats (my kids are grown so we now have cats instead).

**Comment by jglovier** [comment]
Thanks again for attending, everyone! Enjoy the rest of the conference. :wave:
