### ISSUE TITLE
I'm Krista!

### ISSUE THREAD

**Issue by kristaleemcphee** [jglovier/github-for-developers-squares-conf-2016#3]
Hi everyone,

My name is Krista McPhee and I'm from British Columbia ( Canada). I work remote as well for 2 companies - Reaktiv Studios and WP Site Care.  I mainly work in support, and develop a small amount for Design Palette Pro child themes.  I have worked a bit with Github, and have a basic foundation, but haven't really put it into practice.  I'm really looking forward to this class and hanging out and learning new stuff.

See you soon!

**Comment by jglovier** [comment]
Hi @missmiija! Look forward to seeing you Wednesday. :tada:
