### ISSUE TITLE
Howdy from TX!

### ISSUE THREAD

**Issue by nlabhart** [jglovier/github-for-developers-squares-conf-2016#4]
My name is Noah Labhart, I'm the Owner, Lead Mobile Developer at Touchtap (http://touchtap.io). We develop beautiful native mobile experiences (apps) for iOS & Android. I've been developing software for 10ish years, and mobile apps for 3ish. I've been using git for the last couple of years, and really dig it. 

Interesting fact about me is for stress relief, relaxation, I like to split wood. Don't burn it much, cause TX is hot! 👍 Looking forward to meeting you @jglovier and everyone else!

**Comment by jglovier** [comment]
Look forward to seeing you tomorrow, Noah!
